sudo: required
services:
  - docker
language: java
jdk:
  - openjdk10
before_install:
  - sh -c '(echo "#!/usr/bin/env sh" && curl -L https://github.com/lihaoyi/mill/releases/download/0.2.6/0.2.6) > ~/mill && chmod +x ~/mill'
install:
  - ~/mill scalaxb.publishLocal
script:
  - (cd example; ~/mill hello.compile)
  - grep Generated out/hello/scalaxbGeneratedSources/dest/*.scala
  - file out/hello/compile/dest/classes/example/Request.class

